import { NgComponentOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  type Type,
  inject,
  input,
  resource,
  signal,
} from '@angular/core';
import { ForTabs, ForTabsContent, ForTabsList, ForTabsTrigger } from 'forty-cdk';

/**
 * Renders a live preview of a real Angular component alongside its source
 * code. The example file is referenced by relative path under
 * `projects/forty-cdk-docs/src/examples/`, e.g. `<for-example src="disclosure/basic"/>`.
 *
 * Both the component and the source code are loaded via `import.meta.glob`
 * with `eager: false`, so every example becomes its own lazy Vite chunk —
 * the primitive page bundle stays free of the library + every other
 * example until the user navigates to that route.
 *
 * The Preview/Code switcher dogfoods `ForTabs` from the library itself.
 * Panels stay mounted (the library's idiomatic recommendation for Tabs);
 * `ForTabsContent` reflects `aria-hidden` + `inert` while inactive and CSS
 * hides the inactive panel.
 */
// Component is loaded from the `.ts` file (compiled by the Angular plugin)
// for the live preview. Source code is loaded from a sibling `.ts.txt` file
// generated by `scripts/sync-example-sources.ts` — that file extension is
// outside the Angular plugin's match set, so `?raw` returns the original
// TypeScript the consumer is meant to read/copy, not compiled Ivy output.
const componentLoaders = import.meta.glob<{ default: Type<unknown> }>(
  '../../examples/**/*.ts',
);

const sourceLoaders = import.meta.glob<string>('../../examples/**/*.ts.txt', {
  query: '?raw',
  import: 'default',
});

interface ExampleResource {
  component: Type<unknown>;
  source: string;
}

@Component({
  selector: 'for-example',
  imports: [NgComponentOutlet, ForTabs, ForTabsList, ForTabsTrigger, ForTabsContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: `
    :host {
      display: block;
      margin: 1.5rem 0;
    }
  `,
  template: `
    <div
      forTabs
      [(value)]="tab"
      class="overflow-hidden rounded-[10px] border border-border-soft bg-surface-elevated"
    >
      <div forTabsList class="flex gap-1 border-b border-border-soft px-2 pt-2">
        <button
          forTabsTrigger
          value="preview"
          class="
            cursor-pointer rounded-t-[6px] border-0 bg-transparent
            px-3.5 py-1.5 font-[inherit] text-[0.85rem] text-inherit opacity-65
            data-[state=active]:bg-surface-muted data-[state=active]:opacity-100
            focus-visible:outline focus-visible:outline-2
            focus-visible:-outline-offset-2 focus-visible:outline-accent
          "
        >
          Preview
        </button>
        <button
          forTabsTrigger
          value="code"
          class="
            cursor-pointer rounded-t-[6px] border-0 bg-transparent
            px-3.5 py-1.5 font-[inherit] text-[0.85rem] text-inherit opacity-65
            data-[state=active]:bg-surface-muted data-[state=active]:opacity-100
            focus-visible:outline focus-visible:outline-2
            focus-visible:-outline-offset-2 focus-visible:outline-accent
          "
        >
          Code
        </button>
      </div>

      @if (loaded.value(); as data) {
        <div forTabsContent value="preview" class="p-6 data-[state=inactive]:hidden">
          <ng-container *ngComponentOutlet="data.component" />
        </div>
        <div forTabsContent value="code" class="relative data-[state=inactive]:hidden">
          <button
            type="button"
            [attr.data-copied]="copied() ? '' : null"
            (click)="copy(data.source)"
            class="
              absolute right-3 top-2.5 cursor-pointer rounded
              border border-border-strong bg-surface-muted
              px-2.5 py-1 font-[inherit] text-[0.75rem] text-inherit
              data-[copied]:bg-[color-mix(in_oklch,var(--for-success)_28%,transparent)]
            "
          >
            {{ copied() ? 'Copied' : 'Copy' }}
          </button>
          <pre class="m-0 overflow-x-auto bg-surface-muted px-5 py-4 text-[0.85rem]"><code>{{ data.source }}</code></pre>
        </div>
      } @else if (loaded.isLoading()) {
        <div class="p-6 text-[0.9rem] opacity-70">Loading example…</div>
      } @else if (loaded.error()) {
        <div class="p-6 text-[0.9rem] opacity-70">
          Example not found:
          <code class="rounded-[3px] bg-border-soft px-1 py-0.5">{{ src() }}</code>
        </div>
      }
    </div>
  `,
})
export class ForExample {
  /**
   * Path of the example file relative to `src/examples/`, without the `.ts`
   * extension. Example: `'disclosure/basic'` resolves to
   * `src/examples/disclosure/basic.ts`.
   */
  readonly src = input.required<string>();

  protected readonly tab = signal<'preview' | 'code'>('preview');
  protected readonly copied = signal(false);

  readonly #doc = inject(DOCUMENT);

  readonly loaded = resource<ExampleResource | null, string>({
    params: () => this.src(),
    loader: async ({ params: src }) => {
      if (!src) return null;
      const cmpLoader = componentLoaders[`../../examples/${src}.ts`];
      const srcLoader = sourceLoaders[`../../examples/${src}.ts.txt`];
      if (!cmpLoader || !srcLoader) return null;
      const [cmpMod, source] = await Promise.all([cmpLoader(), srcLoader()]);
      return { component: cmpMod.default, source };
    },
  });

  protected async copy(source: string): Promise<void> {
    const win = this.#doc.defaultView;
    if (!win?.navigator?.clipboard) return;
    try {
      await win.navigator.clipboard.writeText(source);
      this.copied.set(true);
      win.setTimeout(() => this.copied.set(false), 1600);
    } catch {
      // Clipboard API can reject in iframes / insecure contexts — silently
      // ignore; the source is still visible in the Code tab for manual copy.
    }
  }
}
