import { NgComponentOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  type Type,
  inject,
  input,
  resource,
  signal,
} from '@angular/core';
import { ForTabs, ForTabsContent, ForTabsList, ForTabsTrigger } from 'forty-cdk';

/**
 * Renders a live preview of a real Angular component alongside its source
 * code. The example file is referenced by relative path under
 * `projects/forty-cdk-docs/src/examples/`, e.g. `<for-example src="disclosure/basic"/>`.
 *
 * Both the component and the source code are loaded via `import.meta.glob`
 * with `eager: false`, so every example becomes its own lazy Vite chunk —
 * the primitive page bundle stays free of the library + every other
 * example until the user navigates to that route.
 *
 * The Preview/Code switcher dogfoods `ForTabs` from the library itself.
 * Panels stay mounted (the library's idiomatic recommendation for Tabs);
 * `ForTabsContent` reflects `aria-hidden` + `inert` while inactive and CSS
 * hides the inactive panel.
 */
// Component is loaded from the `.ts` file (compiled by the Angular plugin)
// for the live preview. Source code is loaded from a sibling `.ts.txt` file
// generated by `scripts/sync-example-sources.ts` — that file extension is
// outside the Angular plugin's match set, so `?raw` returns the original
// TypeScript the consumer is meant to read/copy, not compiled Ivy output.
const componentLoaders = import.meta.glob<{ default: Type<unknown> }>(
  '../../examples/**/*.ts',
);

const sourceLoaders = import.meta.glob<string>('../../examples/**/*.ts.txt', {
  query: '?raw',
  import: 'default',
});

interface ExampleResource {
  component: Type<unknown>;
  source: string;
}

@Component({
  selector: 'for-example',
  imports: [NgComponentOutlet, ForTabs, ForTabsList, ForTabsTrigger, ForTabsContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div forTabs [(value)]="tab" class="for-example">
      <div forTabsList class="for-example__tabs">
        <button forTabsTrigger value="preview">Preview</button>
        <button forTabsTrigger value="code">Code</button>
      </div>

      @if (loaded.value(); as data) {
        <div forTabsContent value="preview" class="for-example__panel for-example__preview">
          <ng-container *ngComponentOutlet="data.component" />
        </div>
        <div forTabsContent value="code" class="for-example__panel for-example__code">
          <button
            type="button"
            class="for-example__copy"
            [attr.data-copied]="copied() ? '' : null"
            (click)="copy(data.source)"
          >
            {{ copied() ? 'Copied' : 'Copy' }}
          </button>
          <pre><code>{{ data.source }}</code></pre>
        </div>
      } @else if (loaded.isLoading()) {
        <div class="for-example__status for-example__loading">Loading example…</div>
      } @else if (loaded.error()) {
        <div class="for-example__status for-example__error">
          Example not found: <code>{{ src() }}</code>
        </div>
      }
    </div>
  `,
  styles: `
    :host {
      display: block;
      margin: 1.5rem 0;
    }
    .for-example {
      border: 1px solid var(--for-border);
      border-radius: 10px;
      overflow: hidden;
      background: var(--for-surface-elevated);
    }
    .for-example__tabs {
      display: flex;
      gap: 0.25rem;
      padding: 0.5rem 0.5rem 0;
      border-bottom: 1px solid var(--for-border);
    }
    .for-example__tabs [forTabsTrigger] {
      padding: 0.4rem 0.9rem;
      font: inherit;
      font-size: 0.85rem;
      background: transparent;
      border: none;
      border-radius: 6px 6px 0 0;
      color: inherit;
      opacity: 0.65;
      cursor: pointer;
    }
    .for-example__tabs [forTabsTrigger][data-state='active'] {
      opacity: 1;
      background: var(--for-surface-muted);
    }
    .for-example__tabs [forTabsTrigger]:focus-visible {
      outline: 2px solid var(--for-accent);
      outline-offset: -2px;
    }
    .for-example__panel[data-state='inactive'] {
      display: none;
    }
    .for-example__preview {
      padding: 1.5rem;
    }
    .for-example__code {
      position: relative;
    }
    .for-example__copy {
      position: absolute;
      top: 0.6rem;
      right: 0.75rem;
      padding: 0.3rem 0.65rem;
      font: inherit;
      font-size: 0.75rem;
      border: 1px solid var(--for-border-strong);
      border-radius: 4px;
      background: var(--for-surface-muted);
      color: inherit;
      cursor: pointer;
    }
    .for-example__copy[data-copied] {
      background: color-mix(in oklch, var(--for-success) 28%, transparent);
    }
    .for-example__code pre {
      margin: 0;
      padding: 1rem 1.25rem;
      overflow-x: auto;
      font-size: 0.85rem;
      background: var(--for-surface-muted);
    }
    .for-example__status {
      padding: 1.5rem;
      opacity: 0.7;
      font-size: 0.9rem;
    }
    .for-example__error code {
      background: var(--for-border);
      padding: 0.05rem 0.3rem;
      border-radius: 3px;
    }
  `,
})
export class ForExample {
  /**
   * Path of the example file relative to `src/examples/`, without the `.ts`
   * extension. Example: `'disclosure/basic'` resolves to
   * `src/examples/disclosure/basic.ts`.
   */
  readonly src = input.required<string>();

  protected readonly tab = signal<'preview' | 'code'>('preview');
  protected readonly copied = signal(false);

  readonly #doc = inject(DOCUMENT);

  readonly loaded = resource<ExampleResource | null, string>({
    params: () => this.src(),
    loader: async ({ params: src }) => {
      if (!src) return null;
      const cmpLoader = componentLoaders[`../../examples/${src}.ts`];
      const srcLoader = sourceLoaders[`../../examples/${src}.ts.txt`];
      if (!cmpLoader || !srcLoader) return null;
      const [cmpMod, source] = await Promise.all([cmpLoader(), srcLoader()]);
      return { component: cmpMod.default, source };
    },
  });

  protected async copy(source: string): Promise<void> {
    const win = this.#doc.defaultView;
    if (!win?.navigator?.clipboard) return;
    try {
      await win.navigator.clipboard.writeText(source);
      this.copied.set(true);
      win.setTimeout(() => this.copied.set(false), 1600);
    } catch {
      // Clipboard API can reject in iframes / insecure contexts — silently
      // ignore; the source is still visible in the Code tab for manual copy.
    }
  }
}
